# Generated by Django 4.2.27 on 2025-12-11 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_comment_options_alter_post_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='challange',
            field=models.SlugField(default='a_slug'),
        ),
    ]
