# Generated by Django 4.2.27 on 2025-12-11 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_comment_challange'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='challange',
            field=models.SlugField(default=3.0),
        ),
    ]
